### ISSUE TITLE
showing certain console info

### ISSUE THREAD

**Issue by Nuclearpotato69** [Tiiffi/mcrcon#100]
i would like to have it show info from the console like when a player issues a cmd but it doesn't show up on rcon but shows up on the server console on my laptop is there a way to make this happen?

**Comment by lerarosalene** [comment]
RCON itself as a protocol doesn't support this.
https://developer.valvesoftware.com/wiki/Source_RCON_Protocol

Server only sends responses to client, it can't stream regular data from logs. Use `tmux` over `ssh`.
