### ISSUE TITLE
Please use release feature

### ISSUE THREAD

**Issue by srakitnican** [Tiiffi/mcrcon#12]
As I am packaging this sources, I have no way to reference a release other then using git snapshots. Please consider using GitHub's release feature, so that code can be referenced by release to a specific point in time.

**Comment by Tiiffi** [comment]
Yeah it's a good idea.

Here is the current version from master branch: https://github.com/Tiiffi/mcrcon/releases/tag/v0.0.5

I am in process of cleaning and rewriting parts of the code so next release should be out soon.
