### ISSUE TITLE
GitHub and Sourceforge sources differ

### ISSUE THREAD

**Issue by srakitnican** [Tiiffi/mcrcon#13]
As found here: https://bugzilla.redhat.com/show_bug.cgi?id=1392599 there seems to be some difference between two sources.
```

--- /tmp/github-mcrcon.c	2016-11-12 10:04:36.309383200 +0100
+++ /tmp/sourceforge-mcrcon.c	2012-08-31 00:07:06.000000000 +0200
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2012-2013, Tiiffi <tiiffi -> gmail_dot_com>
+ * Copyright (c) 2012, Tiiffi <tiiffi_at_gmail_dot_com>
  *
  * This software is provided 'as-is', without any express or implied
  * warranty. In no event will the authors be held liable for any damages
@@ -62,7 +62,7 @@
  *  - Program makes use of C99 feature (variable-length arrays) so "-std=gnu99" flag on
  *    GCC-compiler must be used to avoid unecessary warnings.
  *
- *  - Rcon receive buffer is now bigger (2024 bytes -> 10240 bytes).
+ *  - Rcon receive buffer is now bigger (2048 bytes -> 10240 bytes).
  *     * Thanks to 'gman_ftw' @ Bukkit forums.
  *
  *  - Fixed invalid error message when receiving empty rcon packet (10 bytes).
```

**Comment by Tiiffi** [comment]
I am probably going to remove sources from sourceforge servers and Github will be the official source repository. Souceforge is mainly for binary packages for now (probably going to move binaries on Github too).

At the moment I am cleaning up and rewriting some parts of the code so next release will be only on Github.

**Comment by Tiiffi** [comment]
**For now on Github should be considered the only official source repository.**

I noticed that someone created a manpage for mcrcon. May I include it to my next release?
This way the manpage would be version tracked and kept up-to-date with rest of the code.

**Comment by srakitnican** [comment]
Yes please! If @jared-wallace is ok with that, I don't see why not.

**Comment by jared-wallace** [comment]
No problem here :)
