### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Rundik** [Tiiffi/mcrcon#17]
mcrcon.c: In function ‘get_line’:
mcrcon.c:708:10: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(buffer, bsize, stdin);
          ^

**Comment by aitormendez** [comment]
I have de same error tring to compiling mcrcon

**Comment by carlbennett** [comment]
Make sure you're compiling from the `develop` branch.

**Comment by anton-bozhina** [comment]
root@root:~/tools$ cd mcrcon
root@root:~/tools/mcrcon$ git branch
* develop
root@root:~/tools/mcrcon$ make
cc -std=gnu99 -Wall -Wextra -Wpedantic -Os -s -fstack-protector-strong -o mcrcon mcrcon.c
mcrcon.c: In function ‘get_line’:
mcrcon.c:749:2: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  (void) fgets(buffer, bsize, stdin);
  ^

**Comment by terribledevice** [comment]
Anyone ever find a solution for this? I'm also experiencing the same error, either when attempting install from master or develop.

**Comment by carlbennett** [comment]
This isn't an error, it's a warning. Also, I just took the latest HEAD (00b812249fb1792da540d1fec89bb2548f7063f4) of the develop branch and got such no warning or error when I ran `make`.

    $ make
    cc -std=gnu99 -Wall -Wextra -Wpedantic -Os -s -fstack-protector-strong -o mcrcon mcrcon.c
    $ git log -n1

**Comment by Tiiffi** [comment]
It is just a warning like @carlbennett said. You can safely igore it for now.

Howerever if your compiler treats warnings as errors by default (thus halting the compilation), you can try to manually disable compiler _-Werror_ flag by adding **-Wno-error** to your compiler flags.

My latest local develop branch has this fixed but I haven't pushed it to github yet.
