### ISSUE TITLE
Disable color option munges output

### ISSUE THREAD

**Issue by TheWolfJack** [Tiiffi/mcrcon#2]
http://pastebin.com/aSEKDi8c for full compare/detail

CentOS 7
MC 1.7.10
cauldron-1.7.10-1.1236.05.212

**Comment by Tiiffi** [comment]
Looks like different servers are outputting the colors a bit differently. Also CraftBukkit color output has been changed at some point and now the color stripping and color support is somewhat broken. There migh be a need for custom color filters for different servers.

I have already added raw output (_-r flag_) in development branch which should help debugging this problem. This also opens a possibility for custom handling of the colors in the clientside with platform toolchains.

**Comment by cullorblind** [comment]
Might be an encoding thing. Some plugins seem to be using UTF8 multibyte characters.  Stripping the 0xa7 was leaving the 0xc2 character behind.  I fixed mine by adding the following to both sections to strip the extra byte:

```diff
--- mcrcon.c    2015-12-27 13:36:32.618406852 -0600
+++ mcrcon-fix.c        2015-12-27 13:37:40.912262777 -0600
@@ -568,6 +568,9 @@
     if(print_colors == 1) {

         for(i = 0; (unsigned char) packet->data[i] != 0; ++i) {
+            if((unsigned char) packet->data[i] == 0xc2) {
+                continue;
+            }
             if((unsigned char) packet->data[i] == 0xa7) {
                 ++i;
                 print_color(packet->data[i]);
@@ -584,6 +587,9 @@
     else
     {
         for(i = 0; (unsigned char) packet->data[i] != 0; ++i) {
+            if((unsigned char) packet->data[i] == 0xc2) {
+                continue;
+            }
             if((unsigned char) packet->data[i] == 0xa7) {
                 ++i;
                 continue;
```

This may be a bit hacky and your mileage may vary, but it works for me.

A better fix may be to detect UTF8 properly, but I'm no programmer.  =)

**Comment by Tiiffi** [comment]
This has been hanging way too long. Will be fixed in next release which should be out soon.

I must admit the whole color printing function is pretty messy so I will be rewriting it.

**Comment by Tiiffi** [comment]
Thank you. Fixed in develop branch.
