### ISSUE TITLE
mcrcon encoding issue?

### ISSUE THREAD

**Issue by r0bis** [Tiiffi/mcrcon#21]
Hi, I installed mcrcon and it connects just fine, but in the terminal I have some sort of encoding problem. My terminal is set to use UTF-8 (gnome 3/arch linux), but up-arrow gives instead of command history output you can see on the bottom line and ? gives this output with strange characters. Could you help with this please?

```
�--------- �Help: Index (1/23) �--------------------
�Use /help [n] to get page n of help.
�Aliases: �Lists command aliases
�Bukkit: �All commands for Bukkit
�Essentials: �All commands for Essentials
�EssentialsSpawn: �All commands for EssentialsSpawn
�Minecraft: �All commands for Minecraft
�/achievement: �A Mojang provided command.
�/afk: �Marks you as away-from-keyboard.
�/antioch: �A little surprise for operators.
> ^[[A
```

Commands seem to work ok, it is just strange characters that get appended
```
> who
ÂThere are Â3Â out of maximum Â20Â players online.
```
That is when I set encoding to Western ISO-8895-1

**Comment by Hagb** [comment]
You can try https://github.com/Tiiffi/mcrcon/pull/20

**Comment by Hagb** [comment]
I have made a pull request to fix a similar problem but nobody answered. My pull request may can help you.
Sorry for my bad English.

**Comment by carlbennett** [comment]
Confirmed #20 fixes this issue

**Comment by r0bis** [comment]
Great, thanks so much - it works well now @carlbennett with your fork. All one could wish for is autocompletion with tab and ability to go through previous commands with Up-arrow, but it is awesome as it is. I wish I had seen your fork earlier.

**Comment by Tiiffi** [comment]
This "strange characters" problem (related to color handling) is fixed in latest develop branch (waiting to be pushed).

@r0bis 
> All one could wish for is autocompletion with tab and ability to go through previous commands with Up-arrow, but it is awesome as it is.

I have been thinking about this. At first glance it sounds trivial but in reality in might be hard to implement in a portable way without using extra libraries such as _curses_.

For now I am trying to keep the source as concise and dependency free as possible.
