### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by qqwo927** [Tiiffi/mcrcon#27]
I am a Chinese student, rented a server, can you tell me how to use RCON?
I don't often in making online, you can contact my email.
My email is “2889613770@qq.com” (qq is China's communication software)
Sorry, my English is not very good, so I use translation software to communicate, may not be accurate.

**Comment by Hagb** [comment]
Hey, this program (mcrcon) can be used in console, and it can also be used by other program.
这个程序（mcrcon）能在命令行下使用，也可以被其它程序调用。
（另外没记错的话，似乎 GitHub 默认情况下会把别人对你的回复发到你登记的邮箱里……）

**Comment by qqwo927** [comment]
Thank you！
