### ISSUE TITLE
incorrect location provided in INSTALL.md

### ISSUE THREAD

**Issue by rroslon** [Tiiffi/mcrcon#28]
hi it seems that on Centos 7 make install installs binaries here:
/usr/local/bin/mcrcon
 instead of 
/usr/share/bin/mcrcon

and same for MAN page which is installed here:
/usr/local/share/man/man1/mcrcon.1

Instead of :
/usr/share/man/man1/mcrcon.1

I think the INSTALL.md should be updated with this information

**Comment by Tiiffi** [comment]
Thank you. Fixed.
