### ISSUE TITLE
Filesystem Hierachy Standard

### ISSUE THREAD

**Issue by sindastra** [Tiiffi/mcrcon#32]
Makefile install location does not adhere to Filesystem Hierachy Standard

```/usr/share``` and ```/usr/local/share``` is meant for architecture independent data files.

The ```mcrcon``` binary, is clearly architecture dependent. The correct path should be ```/usr/local```.

See this document for more info http://www.pathname.com/fhs/pub/fhs-2.3.pdf

I will create a pull request...

**Comment by sindastra** [comment]
The first PR can be ignored, I mistakenly PR'd myself. :sweat_smile:

**Comment by Tiiffi** [comment]
There was a mistake in old [INSTALL.md](https://github.com/Tiiffi/mcrcon/blob/v0.6.1/INSTALL.md) text which probably threw you off.

This has been fixed in current develop branch.
