### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by mschmitt3459** [Tiiffi/mcrcon#36]
Howdy,

I'm trying to compile mcrcon, the latest version, and am getting the following error:

cc -std=gnu99 -Wall -Wextra -Wpedantic -Os -s -fstack-protector-strong -o mcrcon mcrcon.c
mcrcon.c: In function ‘get_line’:
mcrcon.c:752:2: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  (void) fgets(buffer, bsize, stdin);

Can you help me out?

Thanks.

**Comment by Tiiffi** [comment]
Hi,

This is the same issue described here: https://github.com/Tiiffi/mcrcon/issues/17

It's just a warning about ignoring return value of fgets() function.

You can either ignore the warning (should be okay) or download and build [Develop](https://github.com/Tiiffi/mcrcon/tree/develop) branch which has this issue fixed.

Or if you want to patch it yoursef, you could replace line:
https://github.com/Tiiffi/mcrcon/blob/8fdda295e2711571d3f68fe57079ee15003ee150/mcrcon.c#L752
with the fix from Develop branch:
https://github.com/Tiiffi/mcrcon/blob/af5e88b528136f30efd7a86eee1bffb795eb36e3/mcrcon.c#L688-L690

**Comment by mschmitt3459** [comment]
Tiiffi,

Thanks for the extremely prompt response!  I'm a Linux tinkerer, not so
much a developer.  I'm also new to GitHub.  I'm following a tutorial online
with my son to set up a Minecraft server.

The -Wno-error flag didn't work for me.  I patched the code as you
described, and it compiled without issue.

Thanks again!

Micah
