### ISSUE TITLE
Cannot connect on my VPS

### ISSUE THREAD

**Issue by KMikeeU** [Tiiffi/mcrcon#40]
I tried using mcrcon for an ARK: Survival Evolved server. It works perfectly fine in my windows subsystem for linux, but when I try to run it on my vps it does not give me any response whatsoever and eventually times out (see screenshots)
Both run a newly compiled version 0.7.1

WSL:
![WindowsSubsystemForLinux](https://user-images.githubusercontent.com/20937441/73851052-29309780-482d-11ea-97d5-2e41169f0916.png)

VPS:
![VPS](https://user-images.githubusercontent.com/20937441/73851170-541aeb80-482d-11ea-8314-475426e10f7c.png)

**Comment by terokorp** [comment]
mcron is made for Minecraft
