### ISSUE TITLE
Bug with command send

### ISSUE THREAD

**Issue by Sotabi** [Tiiffi/mcrcon#42]
I tried the example on GitHub and using the "create_shortcut.bat" file, but it only signs me automaticly in and the commands were not send :?
I am using Win10.

Used Script:

> `@mcrcon.exe -t -H xxx.xxx.xxx.x -P 25575 -p xxxx -w 5 "say Server is restarting!" save-all stop`

Result
![pic](https://user-images.githubusercontent.com/51969825/75383278-5e844e80-58dc-11ea-89c6-aadd87348fff.png)

**Comment by tmanifold** [comment]
@Sotabi , in case you never found a solution: I'm assuming there is a conflict between terminal mode and the `-w` switch. Try running this without `-t` and see what happens.

**Comment by Tiiffi** [comment]
@tmanifold is right.

It doesn't make sense to use terminal mode and throttled message sending together.

I will probably add some kind check to prevent users doing this (or at least add warning when trying to use flags which doesn't make sense).
