### ISSUE TITLE
Error 111

### ISSUE THREAD

**Issue by garteth** [Tiiffi/mcrcon#46]
I have followed an installation via the linuxize dot com website.

At the stage of connection to the console everything was working fine. I then rebooted my VM and now I get the message

Connection Failed
Error 111: Connection refused

Any ideas?

**Comment by Toxicterror** [comment]
same here, also looking for a solution

**Comment by Tiiffi** [comment]
Duplicate of https://github.com/Tiiffi/mcrcon/issues/55
