### ISSUE TITLE
some commands output empty lines

### ISSUE THREAD

**Issue by py-bot-py** [Tiiffi/mcrcon#47]
so i was playing around with the demo and for some reason, when i try certain commands like 
```
f f
```
it just outputs an empty line, at first i thought it had something to do with factions not being supported for whatever reason but if i do 
```
f help
```
it works fine
also, the f f command outputs on the server, but not in the demo script

**Comment by Tiiffi** [comment]
I cannot reproduce this problem on my test bench.

What server version you are using?
Are you using any extensions, plugins etc?

Also  what is `f f` or `f help` commands are supposed to be doing. As far as I know vanilla server doesn't support such commands. Also mcrcon is just show what the server is sending to user so this is probably serverside problem.

**Comment by py-bot-py** [comment]
oh hey tiffi, the f f and the f help command are from a plugin. the commands i wanted to automate are from plugins. sorry but the server that the program was for is now down so i cant test it anymore...

**Comment by Tiiffi** [comment]
Cannot fix something I cannot reproduce.
