### ISSUE TITLE
Strange caracters in the terminal

### ISSUE THREAD

**Issue by Brownie2002** [Tiiffi/mcrcon#48]
Hello,

When I launch mcron in a linux terminal, the arrows to move inside the line are not recognised :
```bash
brownie@localhost:/tmp/mcrcon$ ./mcrcon -t
Logged in. Type 'quit' or 'exit' to quit.
>help
--------- Help: Index (1/11) --------------------
Use /help [n] to get page n of help.
Aliases: Lists command aliases
Bukkit: All commands for Bukkit
dynmap: All commands for dynmap
Minecraft: All commands for Minecraft
WorldBorder: All commands for WorldBorder
/advancement: A Mojang provided command.
/ban: A Mojang provided command.
/ban-ip: A Mojang provided command.
>ban @test^[[D^[[D
```

The `@test^[[D^[[D` are arrows keystrokes to the left,  after writing `test`

I don't know if the issue is related to the terminal or the software.

Regards,

Brownie

**Comment by tmanifold** [comment]
Usually this is up to how your terminal interprets arrow keys. Which terminal are you using?

**Comment by IPlayZed** [comment]
This is pretty much normal, if those keystrokes are not handled by the programmer. For instance try the `telnet` command and do the same thing, it will yield the same results. Right now you can only use delete (backwards, or the Del button on your keyboard) to correct the input. (But correct me if I am wrong.) I hope this explained it a bit. :D

**Comment by Tiiffi** [comment]
@IPlayZed you are righ.

Catching arrow keys etc. on console requires a bit more involved and platform specific code and that is the reason I haven't implemented it.

My goal was to keep the source code relatively simple and concise. I also tried to avoid 3rd party libary dependencies.

Proper console inputs with arrow key and tab support would require either TUI library like curses or alternatively platform specific implementations for every relevant platform.

**Comment by sludin** [comment]
FWIW I just added a pull request to incorporate readline for linux/osx (don't know enough WIN32 any more to even be dangerous).  I think this takes care of this and issue #51 as well.

**Comment by Tiiffi** [comment]
Related to #51
