### ISSUE TITLE
How do you use mcrcon?

### ISSUE THREAD

**Issue by Arthurmeade12** [Tiiffi/mcrcon#59]
Below is the file from which I extracted mcrcon. 
[mcrcon-master.zip](https://github.com/Tiiffi/mcrcon/files/5258405/mcrcon-master.zip)
I can't figure out how to use mcrcon. I ran makefile and it gave me this:
Last login: Mon Sep 21 17:10:45 on ttys001
arthurmeadenew@Arthur-Meade ~ % /Users/arthurmeadenew/Desktop/mcrcon-master/Makefile ; exit;
/Users/arthurmeadenew/Desktop/mcrcon-master/Makefile: line 9: EXENAME: command not found
/Users/arthurmeadenew/Desktop/mcrcon-master/Makefile: line 10: PREFIX: command not found
INSTALL: =: No such file or directory
/Users/arthurmeadenew/Desktop/mcrcon-master/Makefile: line 13: LINKER: command not found
RM: =: No such file or directory
RM: rm: No such file or directory
RM: -v: No such file or directory
RM: -f: No such file or directory
clang: error: no such file or directory: '='
clang: error: no such file or directory: 'gcc'
clang: error: no input files
/Users/arthurmeadenew/Desktop/mcrcon-master/Makefile: line 17: CFLAGS: command not found
/Users/arthurmeadenew/Desktop/mcrcon-master/Makefile: line 18: EXTRAFLAGS: command not found
/Users/arthurmeadenew/Desktop/mcrcon-master/Makefile: line 20: syntax error near unexpected token `$(OS),'
/Users/arthurmeadenew/Desktop/mcrcon-master/Makefile: line 20: `ifeq ($(OS), Windows_NT)'

[Process completed]

Is there supposed to be those errors? And when I go into terminal and type in mcrcon it says, 
zsh: command not found: mcrcon
What do I do? I don't really know hardly anything about coding. I am trying to run this on macOS Catalina 10.15.5 and the latest update on the changelog.md file and the top update is 0.7.1, so I assume I am running that. Thanks for the help!!

**Comment by Arthurmeade12** [comment]
Also, I don't know what "The only dependency is support for getopt() from unistd.h" means. Do I run getopt() unistd.h?

**Comment by Hagb** [comment]
Hi, how did you run the Makefile?
To compile mcrcon, you need to run `make` command but not execute `Makefile` directly.

**Comment by Arthurmeade12** [comment]
I just opened the makefile. I didn't type make into terminal. How do I run the make command without executing the makefile directly?

**Comment by Hagb** [comment]
To compile mcrcon, just `cd` to the where the souce code is (for example `cd /Users/arthurmeadenew/Desktop/mcrcon-master/`), and then run `make` or `cc -std=gnu99 -Wpedantic -Wall -Wextra -Os -s -o mcrcon mcrcon.c`. (Refer to [INSTALL.md](https://github.com/Tiiffi/mcrcon/blob/master/INSTALL.md))
Or maybe there is the binary you need in [release](https://github.com/Tiiffi/mcrcon/releases).

**Comment by Tiiffi** [comment]
@Arthurmeade12 

You have to have developers tools installed on your system (namely **gcc** or **clang** + dev libraries and **make** for running the Makefile).

I am not very familiar with macOS so I don't really know what is the preferred way to install these tools (Maybe Homebrew or perhaps the tools are coming with Xcode?).

If [Homebrew](https://brew.sh) is familiar to you there is a formula available here: https://github.com/webhippie/homebrew-webhippie/blob/master/Formula/mcrcon.rb

For last-ditch effort you could also download very old Mac OS build from Sourceforge repository: https://sourceforge.net/projects/mcrcon/files/0.0.5/

This version is very old and I cannot guarantee it's working with any server.

---

I would like to provide macOS binaries too but for now I don't see any reasonable way to make binary builds without owning a macOS.

Does anyone have good ideas how to provide macOS builds?

**Comment by Arthurmeade12** [comment]
I have homebrew and clang. I tried to run what Hagb said "and then run make or cc -std=gnu99 -Wpedantic -Wall -Wextra -Os -s -o mcrcon mcrcon.c. (Refer to INSTALL.md)" and it gave me this:
Last login: Tue Sep 22 07:56:22 on ttys000
arthurmeadenew@Arthur-Meade ~ % cd /Users/arthurmeadenew/Desktop/mcrcon-master/
arthurmeadenew@Arthur-Meade mcrcon-master % cc -std=gnu99 -Wpedantic -Wall -Wextra -Os -s -o mcrcon mcrcon.c
ld: warning: option -s is obsolete and being ignored
arthurmeadenew@Arthur-Meade mcrcon-master % make
make: Nothing to be done for `all'.
arthurmeadenew@Arthur-Meade mcrcon-master %
I will try to do run the formula on the homebrew link tiifi provided.

**Comment by Tiiffi** [comment]
Looks like it built succesfully.

You should be able to run it. Try: `./mcrcon -h`

**Comment by Arthurmeade12** [comment]
Thanks! When I type ./mcrcon into terminal it recognizes it as a command and says, "You must give password (-p password).
Try 'mcrcon -h' or 'man mcrcon' for help.". 
Then I ran make install while I was still in the directory of /users/arthurmeadenew/desktop/mcrcon-master/ and it said, 
arthurmeadenew@Arthur-Meade mcrcon-master % make install
ginstall -vD mcrcon /usr/local/bin/mcrcon
make: ginstall: No such file or directory
make: *** [install] Error 1
I don't know what this means. Did it install correctly?
And I haven't tried out the homebrew formula yet, I'll do that now.

**Comment by Arthurmeade12** [comment]
OK I typed in brew and then copied and pasted the formula you provided and at the end of the command line it said, "zsh: parse error near `end'
arthurmeadenew@Arthur-Meade mcrcon-master % ".

**Comment by Arthurmeade12** [comment]
Oh, and I can't test it with the server because I am not at my house, so that will have to wait.

**Comment by Tiiffi** [comment]
@Arthurmeade12 
> make: ginstall: No such file or directory

Looks like you don't have `ginstall` installed on your system.

I think you have to install **GNU coreutils** to make it work: `brew install coreutils`

ps. _It is hard to help without access to real macOS to test these things._

**Comment by Arthurmeade12** [comment]
Thank you very much! and thank you for helping me even though you don't have access to a real macOS. And brew install coreutils worked. Thanks!!

**Comment by Arthurmeade12** [comment]
I ran make install and it worked. Thank you!!!!
Now that it's installed, to use it I just go into terminal and use ./mcrcon and then all the arguments I want, right?

**Comment by Arthurmeade12** [comment]
And based on what the readme.md document says you must enclose Minecraft commands in "(example)"? (in quotes)

**Comment by Tiiffi** [comment]
Now you should be able to run command with mcrcon.

For example:
- If you want to get list of users from server:
> `mcrcon -H server-address -p password list`
- Send multiple commands to server:
> 'mcrcon -H server-address -p passowrd "say Server is stopping!" save-all stop`
- Or if you want to connect in terminal mode:
> `mcrcon -H server-address -p password`

**Comment by Arthurmeade12** [comment]
This is all great, but when I try to run the `./mcrcon -H (IP address)`
it says: zsh: permission denied ./mcrcon. Thank you for all the help!!

**Comment by Tiiffi** [comment]
For local executable (the one in your build directory) you have to set execution permissions: `chmod +x mcrcon`

But since you succesfully installed mcrcon you should be able to run it from anywhere just by typing `mcrcon` without `./` prefix.

**Comment by Arthurmeade12** [comment]
Thank you! I tested it last night and it worked! rcon connected. Thank you!!

**Comment by Arthurmeade12** [comment]
Can I close the issue?

**Comment by Tiiffi** [comment]
Yeah sure if the problem is solved.
