### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by LorcanChinnock** [Tiiffi/mcrcon#61]
Getting "Authentication Failed" when trying to connect
Password being used is from a password generator: TPAklk1UlV56%5PSi7^

![image](https://user-images.githubusercontent.com/20125033/100331395-00e67500-2fc8-11eb-9460-ecdc0805c1fb.png)

I can see request is actually getting through to the server as it is spinning up an rcon thread
![image](https://user-images.githubusercontent.com/20125033/100331531-2ffce680-2fc8-11eb-9e02-e7436c57a838.png)

Server Properties:
![image](https://user-images.githubusercontent.com/20125033/100331682-620e4880-2fc8-11eb-9ba0-d259444cfed6.png)

Side note: Tried logging in with https://play.google.com/store/apps/details?id=com.jakubtomana.hypercon.minecraft&hl=en&gl=US and it works fine

**Comment by Tiiffi** [comment]
Hello,

I did some testing yesterday and so far I couldn't reproduce the problem on my setup.

- What version of server you are using?
- Which operating system does the server run on?

**Comment by LorcanChinnock** [comment]
> Hello,
> 
> I did some testing yesterday and so far I couldn't reproduce the problem on my setup.
> 
> * What version of server you are using?
> * Which operating system does the server run on?

Running forge-1.16.1-32.0.108 on AWS EC2, OS: Amazon Linux 2 AMI (ARM)

**Comment by Tiiffi** [comment]
Hi,

This is just a guess but I am suspecting that Windows command line is doing something weird with the special characters in the password.

Try to put the password inside quotes and see if it works that way: `mcrcon -H host -p "TPAklk1UlV56%5PSi7^" "say test"`

**Comment by LorcanChinnock** [comment]
> mcrcon -H host -p "TPAklk1UlV56%5PSi7^" "say test"

Wrapping in " makes it work

**Comment by CNMCRT** [comment]
I used this method, but it still shows "authentication failed!". How should I fix it?
![HI$)EHM2E%TKGEQKA5(4J(5](https://github.com/Tiiffi/mcrcon/assets/133366091/bedcbcee-57f5-4b94-b31b-50ef59807d48)
