### ISSUE TITLE
How to install mcrcon on windows

### ISSUE THREAD

**Issue by lilDill** [Tiiffi/mcrcon#63]
I don't have a lot of experience in all of this and I have a few questions.
Do I run the installation in the command line?
I cloned the reposetory, did `cd mcrcon` but when I try to run `make` it prompts an error message along the lines of "unkown command" (I don't know the exact translation because my cmd is not in english). The install.md says something about C Library and POSIX getopt support dependencys but I have no clue how I would install these if it was the problem. 
Can someone help me how to install mcrcon properly?

**Comment by Koxiaet** [comment]
You will need to install MinGW for it to work.

**Comment by Tiiffi** [comment]
You can also download precompiled binary for Windows: https://github.com/Tiiffi/mcrcon/releases/download/v0.7.1/mcrcon-0.7.1-windows-x86-32.zip

You can always find latest releases here: https://github.com/Tiiffi/mcrcon/releases/latest

**Comment by Slddev** [comment]
When i run mcrcon.exe from the precompiled binary, it shows up for a few milliseconds then its gone. How to fix this?

**Comment by lilDill** [comment]
> When i run mcrcon.exe from the precompiled binary, it shows up for a few milliseconds then its gone. How to fix this?
> 

You have to run the launch.bat and follow the instructions, because the .exe needs parameters. You could also run the .exe via the cmd and pass arguments in the command but I don't know the syntax for that.

**Comment by Tiiffi** [comment]
> When i run mcrcon.exe from the precompiled binary, it shows up for a few milliseconds then its gone. How to fix this?

mcrcon is command line tool so you have to open [command line (cmd.exe)](https://en.wikipedia.org/wiki/Cmd.exe) first and then run mcrcon.

ps. _Older versions of Windows package used to have "launch.bat" script to start mcrcon and query for login. Maybe I should start including it in the further Windows releases again._
