### ISSUE TITLE
mcron c-tcl

### ISSUE THREAD

**Issue by ghost** [Tiiffi/mcrcon#7]
Hi there, just wondering if you could make a tcl version of this great tool to be used with eggdrop bots to control Minecraft servers via IRC?

**Comment by Zequan** [comment]
Basically a tcl script that uses the rcon protocol to use commands like "!server status" which would display "Server: Running/Server: Stopped" "!server start/stop/restart" etc.

**Comment by Tiiffi** [comment]
I am not familiar with TCL but I think it could be possible to use mcrcon via TCL script on eggdrop. That should be the fastest way to implement the feature without writing the whole thing in TCL.

At the moment I am in the process of fixing coloring support and cleaning up the codebase. After I am done I will look into this feature. Of course any TCL knowledge would be appreciated.

**Comment by terokorp** [comment]
Server only can be stopped via rcon, but not started.
If you run eggdrop and mc server on same computer I think easest way is just make startup script to save pid file check will pid exists with tcl script.
I use CraftIRC as minecraft / irc gateway (gateway feature can be disabled) and it can reload server and do some various stuff, no rcon needed for that.
