### ISSUE TITLE
Flaky responses to commands issued when using MCRCON console

### ISSUE THREAD

**Issue by sspearing** [Tiiffi/mcrcon#73]
The responses to commands issued on the MCRCON console are missing, incomplete or inconsistent (read very frustrating).

I'm running a Minecraft-Spigot server using Docker-Compose with luckperms and essentialsX.  This is all running on my Asustor NAS  I'm using the latest Windows version of MCRCON to connect to the Minecraft server and using it, I can issue game commands that have the desired effect.    However MCRON does not bring the responses back properly.  Typing '?' gives the help screen but typing '? luckperms' gives just a basic 2 line response except once in a while I will get a list of lp commands.  If I repeat the exact command, I will get a difference more basic response.  If I type in a full 'lp' command, for instance
 `lp user <username> permission set luckperms.* true`
it will work but I will get no response in MCRCON.  If I type `lp editor`, I get nothing.

I am new to this so if there is something basic I'm missing please let me know.  I can send my yml file if you think it will help.

**Comment by Tiiffi** [comment]
I have to do some testing with those plugins enabled.

Currently mcrcon doesn't support multipacket responses so this might be the problem here. 🤔

**Comment by sspearing** [comment]
I am seeing similar behaviour from the other rcon clients I have tried after working with yours.  So I'm thinking that opening this issue was a mistake on my part.  Your client at least renders the colours nicely unlike the others.  Sorry for the distraction.
