### ISSUE TITLE
Environment variables don't work

### ISSUE THREAD

**Issue by sugoidogo** [Tiiffi/mcrcon#77]
Both in systemd and via bash script I can't get mcrcon to recognize my environment variables unless I `export` them, which systemd doesn't do. This is non-standard behavior for reading environment variables, which means they can't be used with systemd.
```bash
root@minecraft:~# MCRCON_PORT=25575
root@minecraft:~# MCRCON_PASS=password
root@minecraft:~# echo $MCRCON_PORT $MCRCON_PASS
25575 password
root@minecraft:~# mcrcon
You must give password (-p password).
Try 'mcrcon -h' or 'man mcrcon' for help.
root@minecraft:~# export MCRCON_PORT
root@minecraft:~# export MCRCON_PASS
root@minecraft:~# echo $MCRCON_PORT $MCRCON_PASS
25575 password
root@minecraft:~# mcrcon
Connection failed.
Error 111: Connection refused
```
I was expecting `Connection failed` on the first run of `mcrcon`, got `You must give password (-p password).` instead.

**Comment by Hagb** [comment]
It is not about mcrcon. In bash, `MCRCON_PORT` and `MCRCON_PASS` in this case hadn't been environment variables until `export` was used for them. The behavour in this case is actually what should happen.

The following command can also be used for running `mcrcon` with this two environment variables temporarily set:
``` bash
MCRCON_PORT=25572 MCRCON_PASS=password mcrcon
```

**Comment by josephsmendoza** [comment]
What about systemd? I have a unit file:
```
...
EnvironmentFile=/opt/minecraft/.env
...
ExecStop=mcrcon save-all stop
...
```
/opt/minecraft/.env:
```
MCRCON_PORT="25575"
MCRCON_PASS="password"
```

**Comment by Hagb** [comment]
> What about systemd? I have a unit file:
> 
> ```
> ...
> EnvironmentFile=/opt/minecraft/.env
> ...
> ExecStop=mcrcon save-all stop
> ...
> ```
> 
> /opt/minecraft/.env:
> 
> ```
> MCRCON_PORT="25575"
> MCRCON_PASS="password"
> ```

Does it work?

**Comment by josephsmendoza** [comment]
No, that's why I'm asking about it.

**Comment by Hagb** [comment]
Could you paste your entire unit file and output of `sudo systemctl status NAME_OF_THE_UNIT` after you try to start the unit?

**Comment by josephsmendoza** [comment]
Unfortunately my server just had a catastrophic failure, so it's gonna take me a while to get back to the point I can provide that. Will update when I can.

**Comment by Tiiffi** [comment]
Closing this issue.

Please open new one if issue persists.
