### ISSUE TITLE
Automatic Filling

### ISSUE THREAD

**Issue by FantonFancy** [Tiiffi/mcrcon#78]
is it possible to edit .bat or .exe so when i run lauch.bat it will autofill credentials?

**Comment by terokorp** [comment]
On .bat file you can use -p parameter to set password like
`mcrcon -H my.minecraft.server -p this_is_passsword -w 5 "say Server is restarting!" save-all stop`

or use environment variables (listed here: https://github.com/Tiiffi/mcrcon#usage )
like this
```
set MCRCON_HOST=my.minecraft.server
set MCRCON_PASS=this_is_password
mcrcon -w 5 "say Server is restarting!" save-all stop
```

**Comment by Tiiffi** [comment]
Hi,

Windows release of mcrcon should come with `create_shortcut.bat` batch script which will prompt user with credentials and create new `.bat` file to automatically connect to user defined server.
