### ISSUE TITLE
where can i find the dependencies..

### ISSUE THREAD

**Issue by ImAnkl3** [Tiiffi/mcrcon#81]
sorry for such a stupid question, but i'm really not sure where to find "C Library" and "POSIX getopt support",

pc is Windows 10, if that helps? not sure.. i've tried googling but i didnt find anything :( sorry

**Comment by Tiiffi** [comment]
Hi,
Sorry it took so long to anwser.

If you don't want to compile the program you can always dowload latest Windows release: here: https://github.com/Tiiffi/mcrcon/releases/latest

---

If you want to compile from sources the easiest way on Windows is to install MinGW + GCC which has Posix support and every dependency needed.

My personal recommendation is TDM GCC: https://jmeubank.github.io/tdm-gcc/
