### ISSUE TITLE
server.properties gets reset when using mcrcon

### ISSUE THREAD

**Issue by BigBoyChnusti** [Tiiffi/mcrcon#85]
Hi,
So the following happens when i try to connect to my console via mcrcon.
My server properties file is setup with the mcrcon parameters.
Generic Port
Generic Password
Enabled 
Then i restart the minecraft.service i created to reload the properties file.
I connect with : /opt/minecraft/tools/mcrcon/mcrcon -H 127.0.0.1 -P 25575 -p strong-password -t
And i get en Error 111
After that when i check the server.properties the parameters for mcrcon are gone.

**Comment by taranda** [comment]
When I had this problem, I was adding the `mcron-enabled=true` and `rcon.password=...` to `server.properties`.  However, these properties already exist in `server.properties` further down the file, so the ones I set we being overridden.  Do not add these properties, rather edit the existing ones.

**Comment by terokorp** [comment]
This is minecraft server setup problem, and not related to mcrcon. Closing
