### ISSUE TITLE
Compiling on windows

### ISSUE THREAD

**Issue by hammyexe** [Tiiffi/mcrcon#88]
I am using the TDM-GCC 10.3.0 release, and I git clone, proceed to cd into the folder, then do a make, and sudo make install. Whenever I type in the terminal, ".\mcrcon.exe" it asks for the right syntax, but it doesnt work, even if I do mcrcon -H localhost -p (password), it works on my linux machine though.

**Comment by MMitsuha** [comment]
can you give the original output of the program?

**Comment by terokorp** [comment]
As @caizhe666 already told, we need original output/error message.
And because this question is already quite old, I will close this issue. If problem still persist, feel free to reopen.
