### ISSUE TITLE
Executing in Different Worlds?

### ISSUE THREAD

**Issue by LeeSchoenwetter** [Tiiffi/mcrcon#9]
I am trying to execute a series of commands in "The End", and I can run them from the command line in the game, but not from within MCRCON.  Any thoughts?  (a "worldswitch" command? something like that?). Much appreciated!  Love the tool. Works great on my server.  Thanks!

**Comment by Tiiffi** [comment]
Could you be more specific which commands do not work and what happens when you try to use them?

**Comment by LeeSchoenwetter** [comment]
Yeah - thanks for getting back to me.

When in “The End”, if I try logging in from my local system using MCRCON, and trying to place blocks in XYZ coordinates in the end… it tells me that the points are outside of the world (meaning, no one is active in that region top-side).

It seems that from MCRCON, all commands are assumed to be executing topside, not in the Nether or The End.

Make sense?

Let me know… I’m happy to try testing some stuff, and you’re welcome to come into game with me when I do.  Feel free to call, if that works better, number below!


Thanks again for taking the time to respond.  I love the product… I’ve been able to do some VERY cool stuff using the tool.

Are you familiar with PHP?  I wrote a php script that generated lines I could paste into mcrcon, which cleared out an entire ocean region to the bedrock, and then inserted a glass globe into the middle of it, with a 64-block radius. Starting to build up layers in it now, water, lave, rock, etc… then will build a castle in it, as a “central hub” in my world.  Should be fun.






Lee Schoenwetter
lee.schoenwetter@me.com
937-231-1732

**Comment by Tiiffi** [comment]
Okay so it seems that server assumes that rcon commands are excuted always on the topside. This is server-side problem AFAIK.

We have to investigate if there is a way to execute commands in different dimensions (some command arguments perhaps?).

**Comment by LeeSchoenwetter** [comment]
Tiiffi -

Have been giving this some additional thought…  found a possible solution, though I’m not sure the best way to implement it.

Looks like the “RemoteControlCommandListener.java” file is automatically getting the “world” from the server…  my thought is that for my local server… I could just check to see if I am online, get my world, and return the default, otherwise…

public World getWorld() {
        Player playerDonk = Bukkit.getPlayerExact("DonkBloodfost");
        if( playerDonk == null ) {
            return MinecraftServer.getServer().getWorld();
        } else {
            return playerDonk.getLocation().getWorld();
        }
    }

The other option would be to change the individual commands to look for something like MultiVerse uses (w:world_newnether), and if found in the command, execute in that world.  Seems far more complicated.

Any thoughts on other ideas?

Or can you offer any guidance as to how I would implement this change just on my server?  (I’ve tried compiling just that class, but can’t seem to get it to resolve all of the dependencies…)


Just throwing out ideas…




Lee Schoenwetter
lee.schoenwetter@me.com
937-231-1732

**Comment by Technoguyfication** [comment]
I believe the Minecraft RCON protocol is extremely basic and only runs commands as if they were on the server console. You can however, get a plugin to run commands within dimensions from Console / Remote Console.

**Comment by terokorp** [comment]
Mcrcon runs commands in console, not as player. Console is not in any world and it can't select worlds, so basicly you can't set blocks with vanilla commands.
However you can try variabletriggers plugin, it may solve your problem.
http://dev.bukkit.org/bukkit-plugins/variabletriggers/
