### ISSUE TITLE
Wont Open just closes instantly

### ISSUE THREAD

**Issue by AcesGamingUK** [Tiiffi/mcrcon#91]
same issue as #69

windows version 10 
MCRCON version 0.7.2

repro - 
download [mcrcon-0.7.2-windows-x86-64](https://github.com/Tiiffi/mcrcon/releases/download/v0.7.2/mcrcon-0.7.2-windows-x86-64.zip)
unzip
click `mcrcon.exe` to run.

opens and then instantly closes within milliseconds,
unable to give any other info as it does not stay open long enough to get any information

**Comment by terokorp** [comment]
This software has no GUI, you have to run it on console or use batch file to enter parameters.

Check Usage section on README.md
https://github.com/Tiiffi/mcrcon#usage
