### ISSUE TITLE
Can't get mcrcon to work on Windows

### ISSUE THREAD

**Issue by InterstellarOne** [Tiiffi/mcrcon#92]
I am trying to follow a minecraft tutorial that uses blender to connect and control the game. As with issue #82 everything worked correctly up to this point, but after seeming to install mcrcon it still acts like it hasn't been installed. Here's what I get from trying it in command prompt: `C:\Users\Global>mcrcon --help
'mcrcon' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Global>pip install mcrcon
Requirement already satisfied: mcrcon in c:\users\global\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (0.7.0)`

And here's the output from blender: `Defaulting to user installation because normal site-packages is not writeable
Looking in links: c:\Users\Global\AppData\Local\Temp\tmpr1p2x4d2
Requirement already satisfied: setuptools in c:\program files\blender foundation\blender 3.0\3.0\python\lib\site-packages (57.4.0)
Requirement already satisfied: pip in c:\users\global\appdata\roaming\python\python39\site-packages (22.2.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\users\global\appdata\roaming\python\python39\site-packages (22.2.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mcrcon in c:\users\global\appdata\roaming\python\python39\site-packages (0.7.0)
--------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Global\Desktop\BlenderMusicSyncV2\MusicSync.blend\script.py", line 40, in <module>
  File "<string>", line 8, in <module>
ModuleNotFoundError: No module named 'mcrcon'
Error: Python script failed, check the message in the system console`

**Comment by terokorp** [comment]
Hi. This mcron is not python implementation that you have been installed with pip command.
python version seems to be here: https://github.com/uncaught-exceptions/mcrcon (someone uses same name on their package which causing confusion)
But this one, not the pip version, works on windows command prompt like you have tried to use, but you have to execute commands on same folder where you have extracted the files.

**Comment by InterstellarOne** [comment]
Ah thank you.
