### ISSUE TITLE
Make Command Error on Ubuntu Server 22.04

### ISSUE THREAD

**Issue by DrewWeird** [Tiiffi/mcrcon#94]
Make command retruns the following after cloning from git

~/mcrcon$ make
gcc -std=gnu99 -Wall -Wextra -Wpedantic -Os -s -fstack-protector-strong -o mcrcon mcrcon.c
make: gcc: No such file or directory
make: *** [Makefile:35: mcrcon] Error 127

**Comment by Tiiffi** [comment]
Hi,

You have to install compiler to your system first.

for example:
```bash
apt update
sudo apt install gcc libc-dev
```

After that you can compile mcrcon.

**Comment by DrewWeird** [comment]
Thank you, I installed it and all is working now!
