### ISSUE TITLE
"minecraft.service: Failed at step EXEC spawning /var/minecraft/mcrcon/mcrcon: Permission denied"

### ISSUE THREAD

**Issue by Atomicez** [Tiiffi/mcrcon#97]
I am setting up a server in terminal, and dont know what happened. All i knew was, i shut the server down, enabled command blocks in server.properties and tried to start it back up, getting this problem. 
Help please? 
![image_2022-12-01_195757716](https://user-images.githubusercontent.com/87731685/205211746-b94c2a26-3902-4a36-af53-6f96c831b3ce.png)

**Comment by Atomicez** [comment]
no, that is not my ip.

**Comment by terokorp** [comment]
Changing server.properties and/or restarting doesn't cause this kind of problems, something else has changed.
Please check will /var/minecraft/mcrcon/mcrcon file exist? And will it have executable flag (x) set?

**Comment by Atomicez** [comment]
I found the issue, i set the ram up wrong and had to use more ram then i
had
